INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (1, 'ខេត្ត', '1', 'បន្ទាយមានជ័យ', 'Banteay Meanchey');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (2, 'ខេត្ត', '2', 'បាត់ដំបង', 'Battambang');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (3, 'ខេត្ត', '3', 'កំពង់ចាម', 'Kampong Cham');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (4, 'ខេត្ត', '4', 'កំពង់ឆ្នាំង', 'Kampong Chhnang');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (5, 'ខេត្ត', '5', 'កំពង់ស្ពឺ', 'Kampong Speu');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (6, 'ខេត្ត', '6', 'កំពង់ធំ', 'Kampong Thom');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (7, 'ខេត្ត', '7', 'កំពត', 'Kampot');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (8, 'ខេត្ត', '8', 'កណ្ដាល', 'Kandal');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (9, 'ខេត្ត', '9', 'កោះកុង', 'Koh Kong');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (10, 'ខេត្ត', '10', 'ក្រចេះ', 'Kratie');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (11, 'ខេត្ត', '11', 'មណ្ឌលគិរី', 'Mondul Kiri');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (12, 'ខេត្ត', '12', 'រាជធានីភ្នំពេញ', 'Phnom Penh');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (13, 'ខេត្ត', '13', 'ព្រះវិហារ', 'Preah Vihear');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (14, 'ខេត្ត', '14', 'ព្រៃវែង	', 'Prey Veng');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (15, 'ខេត្ត', '15', 'ពោធិ៍សាត់	', 'Pursat');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (16, 'ខេត្ត', '16', 'រតនគិរី	', 'Ratanak Kiri');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (17, 'ខេត្ត', '17', 'សៀមរាប	', 'Siemreap');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (18, 'ខេត្ត', '18', 'ព្រះសីហនុ	', 'Preah Sihanouk');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (19, 'ខេត្ត', '19', 'ស្ទឹងត្រែង	', 'Stung Treng');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (20, 'ខេត្ត', '20', 'ស្វាយរៀង	', 'Svay Rieng');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (21, 'ខេត្ត', '21', 'តាកែវ	', 'Takeo');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (22, 'ខេត្ត', '22', 'ឧត្ដរមានជ័យ	', 'Oddar Meanchey');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (23, 'ខេត្ត', '23', 'កែប	', 'Kep');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (24, 'ខេត្ត', '24', 'ប៉ៃលិន	', 'Pailin');
INSERT INTO province(id, type, postal_code, name_km, name_en) OVERRIDING SYSTEM VALUE VALUES (25, 'ខេត្ត', '25', 'ត្បូងឃ្មុំ	', 'Tboung Khmum');