name: ISLDevs CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run Tests
        run: ./gradlew test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: isldevs-app
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: isldevs-app
          path: app/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Starting deployment..."

            # Create application directory
            mkdir -p ~/isldevs-app

            # Stop any existing application
            pkill -f 'java -jar isldevs.jar' || true
            sleep 2

            # Copy new application
            echo "Copying new JAR file..."
            cp ~/app/*.jar ~/isldevs-app/isldevs.jar

            # Start application
            echo "Starting application..."
            cd ~/isldevs-app
            nohup java -jar isldevs.jar --spring.config.location=classpath:/config/.prod > app.log 2>&1 &

            # Verify deployment
            sleep 5
            echo "Application status:"
            ps aux | grep java | grep -v grep
            echo "Deployment completed successfully!"